---
title: About me
format: html
---

::: {.page-intro}
I’m Pietro and Alice’s dad and Maressa’s husband. Growing up in a low-income household, I started **working at 14**, but I always held onto the belief that education was my way forward. After a childhood in public schools, I made a bold move at 20: I enrolled in **two concurrent degrees** - Economics full-time and Accounting at night. Since I couldn't rely on financial support from my parents, I hustled to make ends meet through **research scholarships, teaching assistantships, junior consulting**, and working as a **computer technician**. It wasn't easy, but I managed to graduate from both.
:::

Driven by a restless curiosity for challenges, I decided to pursue an **academic career** during my second year of undergrad. After being accepted into several programs, I chose the **Master’s in Administration at UFU** to stay close to my roots and marry Maressa. During those two years, I set a record that people still talk about: I produced **35 papers** while on a scholarship. The secret? A genuine passion for statistical analysis and a constant drive to help anyone who knocked on my door.

By 24, I was already a **university professor**. While balancing my Master’s thesis, I dove deeper into **quantitative methods and applied statistics**. This period was a whirlwind: I started my PhD at FEA/USP while passing the civil service exam to teach at the **Federal University of Viçosa (UFV)**. For two years, I spent 24 hours every week on a bus—12 hours each way—traveling between my classes in São Paulo and my students in Viçosa. In 2008, I returned to my hometown as a permanent professor, and by 2011, I earned my **PhD in Finance from FEA/USP** with honors. My track record included **40 published articles**, a thesis with international reach, and the **KPMG/IBEF Revelation Award in Finance**. I even made the headlines in Brazil for a provocative discovery: **I proved that psychological measures could actually improve credit ratings.**

My career has allowed me to teach a wide range of undergraduate and graduate courses—from **Econometrics and Psychometrics to Corporate Finance and Behavioral Finance**. Interacting with hundreds of students and sharing what I know is one of my greatest pleasures. Beyond the classroom, I’ve led dozens of institutional consulting and research projects.

In addition to teaching, more recently I have focused on **quantitative methods literacy** through **tutorial articles** and the creation of **open educational resources**, as well as **statistical, computational, and data literacy**, using **open-source artificial intelligence** aimed at applied social scientists.
